name: inv-mgmt

services:
  client:
    image: ghcr.io/artbok/inventory-management-client:latest
    ports:
      - "60080:80" 
    environment:
      - SERVER_URL=http://localhost:5000
    depends_on:
      - server 

  server:
    image: ghcr.io/artbok/inventory-management-server:latest
    ports:
      - "5000:5000" 
